site_name: Aleshkevich Interactive
author: Jonas Aleshkevich
keywords:
  - Jonas Aleshkevich
  - Jonas
  - Aleshkevich
  - Jonasz
  - Aleszkiewicz
  - LOGIA
  - najlepszy informatyk w Staszicu
  - Competitive Programming
  - algorytmika
  - informatyka
  - algoritmika
